### ISSUE TITLE
You readme is scaring people away

### ISSUE THREAD

**Issue by ariealerr** [elkowar/Desktop-dotfiles#2]
Like your readme is basically a threat to not look at your dots, i mean, if i came here, i obviously want to look at them. I'm not just gonna stumble upon them think: "UwU, wHaT's ThIs?" like no that's not how it works. plz fix.

**Comment by elkowar** [comment]
scaring people away from these is kind of the goal, as i don't want to maintain and support all people that look at them. My configs are rather complicated in many cases, and not really a good place for beginners to look
